# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

CREATE TABLE "users" (
"user_id" bigint generated by default as identity(start with 1) not null primary key,
"user_name" varchar not null);

CREATE TABLE "yt_users" (
  "user_channel_id" varchar(24) not null primary key,
  "user_id" bigint not null,
  CONSTRAINT fk_yt_users_with_users
          FOREIGN KEY ("user_id")
              REFERENCES "users" ("user_id")
);

CREATE TABLE "yt_streamer" (
    "channel_id" varchar(24) NOT NULL PRIMARY KEY,
    "onwer_user_id" bigint not null,
    CONSTRAINT fk_yt_streamer_with_users
              FOREIGN KEY ("onwer_user_id")
                  REFERENCES "users" ("user_id")
);

CREATE TABLE "user_streamer_state"(
    "user_id" bigint not null,
    "streamer_channel_id" varchar(24) NOT NULL,
    "current_balance_number" bigint NOT NULL,
     CONSTRAINT fk_user_streamer_state_with_users
                   FOREIGN KEY ("user_id")
                       REFERENCES "users" ("user_id"),
   CONSTRAINT fk_user_streamer_state_with_streamer
                      FOREIGN KEY ("streamer_channel_id")
                          REFERENCES "yt_streamer" ("channel_id")
);

# --- !Downs
drop table "people" if exists;
drop table "users" if exists;
drop table "yt_users" if exists;
drop table "yt_streamer" if exists;
drop table "user_streamer_state" if exists;