# --- !Ups

-- Add columns to yt_users for Silhouette integration
ALTER TABLE "yt_users" ADD COLUMN IF NOT EXISTS "display_name" VARCHAR;
ALTER TABLE "yt_users" ADD COLUMN IF NOT EXISTS "email" VARCHAR;
ALTER TABLE "yt_users" ADD COLUMN IF NOT EXISTS "profile_image_url" VARCHAR;
ALTER TABLE "yt_users" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "yt_users" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "yt_users" ADD COLUMN IF NOT EXISTS "activated" BOOLEAN DEFAULT FALSE;

-- Create table for OAuth2 tokens
CREATE TABLE "oauth2_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "user_channel_id" VARCHAR(24) NOT NULL,
  "access_token" VARCHAR NOT NULL,
  "token_type" VARCHAR,
  "expires_in" INTEGER,
  "refresh_token" VARCHAR,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fk_oauth2_tokens_yt_users" FOREIGN KEY ("user_channel_id") REFERENCES "yt_users" ("user_channel_id") ON DELETE CASCADE
);

-- Create index for faster token lookups
CREATE INDEX "idx_oauth2_tokens_user_channel_id" ON "oauth2_tokens" ("user_channel_id");

-- Create table for Silhouette login info mapping
CREATE TABLE "login_info" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "provider_id" VARCHAR NOT NULL,
  "provider_key" VARCHAR NOT NULL,
  "user_id" BIGINT NOT NULL,
  CONSTRAINT "fk_login_info_users" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
  CONSTRAINT "unique_login_info" UNIQUE ("provider_id", "provider_key")
);

-- Create index for faster login lookups
CREATE INDEX "idx_login_info_provider_key" ON "login_info" ("provider_id", "provider_key");
CREATE INDEX "idx_login_info_user_id" ON "login_info" ("user_id");

# --- !Downs

-- Drop the created tables
DROP TABLE IF EXISTS "oauth2_tokens";
DROP TABLE IF EXISTS "login_info";

-- Remove added columns from yt_users
ALTER TABLE "yt_users" DROP COLUMN IF EXISTS "display_name";
ALTER TABLE "yt_users" DROP COLUMN IF EXISTS "email";
ALTER TABLE "yt_users" DROP COLUMN IF EXISTS "profile_image_url";
ALTER TABLE "yt_users" DROP COLUMN IF EXISTS "created_at";
ALTER TABLE "yt_users" DROP COLUMN IF EXISTS "updated_at";
ALTER TABLE "yt_users" DROP COLUMN IF EXISTS "activated";
