package models

import java.time.Instant

/**
 * Represents the mapping between a tournament registration and its corresponding Challonge participant ID
 */
case class TournamentChallongeParticipant(
                                           id: Long = 0L, // Sequential ID, will be auto-generated
                                           tournamentId: Long,
                                           userId: Long,
                                           challongeParticipantId: Long, // The participant ID generated by Challonge
                                           challongeTournamentId: Long, // The Challonge tournament ID for reference
                                           createdAt: Instant = Instant.now(),
                                           updatedAt: Instant = Instant.now()
                                         )
